### PR TITLE
Support React 18

### PR DESCRIPTION
**Pull request by swissspidy**
This allows easily using this library in a React 18 app.

### CODE REVIEW

**Comment by just-boris** [comment]
ok, the PR is merged but what about the release? it is unusable if not released

**Comment by KevinVandy** [comment]
> ok, the PR is merged but what about the release? it is unusable if not released

I think @tannerlinsley is the only one who could manually release an update for the old react virtual package. However, v3 is getting closer to stable release.

**Comment by just-boris** [comment]
What is the point of merging but not releasing it? If there are no known issues (at least I can confirm it from our use-case), there is nothing stop releasing it in v2 without requiring much friction from consumers

**Comment by just-boris** [comment]
Sadly, starting from npm v8 they may fail the installation. This is how I have come to this thread

**Comment by connorjs** [comment]
@tannerlinsley - Any chance we can cut a release for v2 that includes this React 18 peer dependency update? (Excited for v3, but releasing this for v2 helps existing installs.)

**Comment by knitevision1** [comment]
@swissspidy @tannerlinsley Is there any way to bump this to release?

`v2.10.4` doesn't have React 18 as peer dependency.

It'll help migrating existing projects to React 18 while keeping v2

**Comment by swissspidy** [comment]
I am not a maintainer here, so I can‘t help with releases. This PR was my only contribution.

**Comment by knitevision1** [comment]
@tannerlinsley :heart:

**Comment by ilchenkoArtem** [comment]
@KevinVandy I encounter an error while trying to update to React 18 and installing packages.

```
Could not resolve dependency:
npm ERR! peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm ERR! node_modules/react-virtual
npm ERR!   react-virtual@"^2.10.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm ERR!   node_modules/react-virtual
npm ERR!     react-virtual@"^2.10.4" from the root project
npm ERR! 
```

Can we add please react 18 to pear-dependency to version 2?

**Comment by mctep** [comment]
@tannerlinsley Is there any chance to publish a new version of the `react-virtual` package? 🙏

**Comment by mctep** [comment]
@piecyk May be you can help somehow?

**Comment by just-boris** [comment]
I figured that maybe package maintainers do not read comments on already closed threads.

Let's try with a new issue instead: https://github.com/TanStack/virtual/issues/568

maybe it will bring some attention

**Pull request merged**
